import { AboutSlint, VerticalBox, HorizontalBox, Button, CheckBox, TextEdit, LineEdit, Palette } from "std-widgets.slint";
import { MainScreen, LinkState, Group } from "main_screen.slint";
import { SettingsScreen, SendMode } from "settings_screen.slint";

enum Screen {
    main,
    settings,
}

component SnackBar {
    in-out property <bool> opened: false;
    in property <duration> show-time: 2s;
    in property <brush> text-color: Palette.foreground;
    in-out property <string> text: "Test text";
    height: 50px;

    Rectangle {
        y: root.opened ? 0 : root.height;
        height: root.height - 8px;
        width: root.width - 8px;
        border-radius: 10px;
        background: Palette.background.brighter(0.3);
        Text {
            text: root.text;
            color: root.text-color;
            // font-size: root.height / 2.5;
            vertical-alignment: center;
            horizontal-alignment: left;
            overflow: elide;
            width: root.width - 20px;
        }
        animate y {
            duration: 150ms;
        }
    }
}

export component App inherits Window {
    title: "Modern Sender";
    preferred-height: 600px;
    preferred-width: 800px;

    in property <string> listener-ip;
    in-out property <[Group]> groups;
    in property <bool> autosend;
    property <Screen> screen: Screen.main;
    in property <SendMode> send-mode;
    in property <int> sync-interval;
    in property <int> send-timeout;

    callback autosync();
    autosync => {
        sync();
        main-scr.is-syncing = true;
    }

    // To native code
    callback start-link <=> main-scr.start-link;
    callback sync();
    callback get-groups <=> main-scr.get-groups;
    callback group-edited <=> main-scr.group-edited;
    callback send-message <=> main-scr.send-message;
    callback autosend-change <=> main-scr.autosend-change;
    callback check-ip-correct <=> sett-scr.check-ip;
    callback send-mode-change <=> sett-scr.send-mode-change;
    callback sync-interval-changed <=> sett-scr.sync-interval-changed;
    callback send-timeout-changed <=> sett-scr.send-timeout-changed;

    // From native code
    callback set-qr <=> main-scr.set-qr;
    callback linked <=> main-scr.linked;
    callback synced <=> main-scr.synced;
    callback set-message-text <=> main-scr.set-message-text;

    // Callbacks for snackbar
    in-out property <bool> notif-open: snackbar.opened;
    callback report(string);
    report(text) => {
        snackbar.text = text;
        snackbar.opened = true;
        report-close-prepare(snackbar.show-time);
    }
    callback report-close-prepare(duration);
    callback report-close();
    report-close => {
        snackbar.opened = false;
    }

    // Actual UI
    main-scr := MainScreen {
        link-state: unlinked;
        groups: root.groups;
        autosend: root.autosend;
        width: 100%;
        height: 100%;
        settings => {
            root.screen = Screen.settings;
        }
        sync => {
            root.sync();
        }
        
        animate x {
             duration: 150ms;
             easing: ease-in-out;
        }
    }
    
    sett-scr := SettingsScreen {
        listener-ip: root.listener-ip;
        send-mode: root.send-mode;
        sync-interval: root.sync-interval;
        send-timeout: root.send-timeout;

        width: 100%;
        height: 100%;
        back => {
            root.screen = Screen.main;
        }
        sync => {
            root.autosync();
        }

        animate x {
             duration: 150ms;
             easing: ease-in-out;
        }
    }

    states [
        main when screen == Screen.main: {
            main-scr.x: 0;
            sett-scr.x: -root.width;
        }
        settings when screen == Screen.settings: {
            main-scr.x: root.width;
            sett-scr.x: 0;
        }
    ]

    snackbar := SnackBar {
        width: root.width;
        x: 0;
        y: root.height - self.height;
    }
}
