import { AboutSlint, VerticalBox, HorizontalBox, Button, CheckBox, TextEdit, LineEdit } from "std-widgets.slint";

export enum LinkState {
    unlinked,
    linking,
    qr,
    linked
}

export struct Group {
    title: string,
    state: bool,
}

component IpEdit inherits LineEdit {
    callback check-ip(text: string) -> bool;
    in-out property <bool> correct: true;

    edited(text) => {
        correct = check-ip(text)
    }
}

export component App inherits Window {
    title: "Message Sender";
    preferred-height: 600px;
    preferred-width: 800px;

    property <LinkState> link-state: unlinked;
    property <image> qr_code;
    property <bool> is-syncing: false;
    in-out property <[Group]> groups;
    in property <string> listener-ip;
    in property <bool> autosend;

    // To native code
    callback start-link();
    callback sync(LinkState);
    callback get-groups();
    callback group-edited(group: string, state: bool);
    callback send-message(message: string);
    callback check-ip-correct(string) -> bool;
    callback autosend-change(bool);

    // From native code
    callback set-qr(image);
    set-qr(qr) => {
        link-state = LinkState.qr;
        qr_code = qr;
    }
    callback linked();
    linked => {
        link-state = LinkState.linked;
        get-groups();
    }
    callback synced();
    synced => {
        is-syncing = false;
        linked();
    }
    callback set-message-text(text: string);
    set-message-text(text) => {
        text-edit.text = text
    }

    // Actuall UI
    HorizontalBox {
        spacing: 10px;

        VerticalBox {
            alignment: center;
            spacing: 20px;
            max-width: 250px;

            HorizontalBox {
                preferred-height: link-lbl.preferred-height;
                alignment: LayoutAlignment.center;

                link-lbl := Text {
                    text: "Message Sender";
                }
                Rectangle {
                    background: root.link-state == LinkState.linked ? Colors.green : Colors.red;
                    border-radius: self.height / 2;
                    height: 10px;
                    width: 10px;
                }
            }
            if link-state == LinkState.unlinked: Button {
                text: "Start Linking";
                clicked => {
                    root.start-link();
                    root.link-state = LinkState.linking;
                }
            }
            if link-state == LinkState.linking || link-state == LinkState.qr: Button {
                text: "Link in progress...";
                enabled: false;
            }
            if link-state == LinkState.qr: Image {
                source: qr_code;
            }
            if link-state == LinkState.linked: Button {
                text: "Sync";
                enabled: !root.is-syncing;
                clicked => {
                    root.sync(link-state);
                    root.is-syncing = true;
                }
            
            }
            if is-syncing: Text {
                text: "Syncing...";
                horizontal-alignment: center;
            }
            for group in root.groups: CheckBox {
                text: group.title;
                checked: group.state;
                toggled => {
                    root.group-edited(group.title, self.checked)
                }
            }
        }

        VerticalBox {
            // alignment: stretch;
            spacing: 20px;

            IpEdit {
                text: root.listener-ip;
                placeholder-text: "Listener IP";
                check-ip(text) => {
                    root.check-ip-correct(text)
                }
            }

            text-edit := TextEdit {
                enabled: true;
                placeholder-text: "Message text";
                wrap: word-wrap;
            }

            Button {
                text: "Send";
                clicked => {
                    send-message(text-edit.text)
                }
            }

            CheckBox {
                checked: root.autosend;
                text: "Send automatically";
                toggled => {
                    root.autosend-change(self.checked)
                }
            }
        }
    }
}
