import { HorizontalBox, VerticalBox, Button, CheckBox, TextEdit, ScrollView, Palette } from "std-widgets.slint";

export enum LinkState {
    unlinked,
    linking,
    qr,
    linked
}

export struct Group {
    title: string,
    state: bool,
}

export component MainScreen {
    in-out property <LinkState> link-state: unlinked;
    property <image> qr_code;
    in-out property <bool> is-syncing: false;
    in-out property <[Group]> groups;
    in property <bool> autosend;

    callback settings();

    
    callback start-link();
    callback sync();
    callback group-edited(string, bool);
    callback send-message(string);
    callback autosend-change(bool);
    callback get-groups();
    
    callback set-qr(image);
    set-qr(qr) => {
        link-state = LinkState.qr;
        qr_code = qr;
    }
    callback linked();
    linked => {
        link-state = LinkState.linked;
        get-groups();
    }
    callback synced();
    synced => {
        is-syncing = false;
        linked();
    }
    callback set-message-text(text: string);
    set-message-text(text) => {
        text-edit.text = text
    }

    TouchArea {}

    HorizontalBox {
        spacing: 10px;

        VerticalBox {
            // alignment: start;
            spacing: 20px;
            max-width: 250px;

            HorizontalBox {
                preferred-height: link-lbl.preferred-height;
                alignment: LayoutAlignment.center;

                Button {
                    icon: @image-url("icons/settings.svg");
                    colorize-icon: true;
                    clicked => {
                        settings();
                    }
                    width: self.preferred-width;
                }

                link-lbl := Text {
                    text: "Modern Sender";
                    font-size: 18px;
                }
                Rectangle {
                    background: root.link-state == LinkState.linked ? Colors.green : Colors.red;
                    border-radius: self.height / 2;
                    height: 10px;
                    width: 10px;
                }
            }
            if link-state == LinkState.unlinked: Button {
                text: "Приєднати пристрій";
                clicked => {
                    root.start-link();
                    root.link-state = LinkState.linking;
                }
            }
            if link-state == LinkState.linking || link-state == LinkState.qr: Button {
                text: "Приєднання...";
                enabled: false;
            }
            if link-state == LinkState.qr: Image {
                source: qr_code;
            }
            if link-state == LinkState.linked: Button {
                text: "Синхронізувати";
                enabled: !root.is-syncing;
                clicked => {
                    root.sync();
                    root.is-syncing = true;
                }
            
            }
            if is-syncing: Text {
                text: "Синхронізація...";
                horizontal-alignment: center;
            }
            
            ScrollView {
                viewport-width: self.width;
                viewport-height: groups.length * (10px + 29px) - 10px;
                // width: 100%;
                height: 100%;

                VerticalLayout {
                    alignment: start;
                    spacing: 10px;

                    for group in root.groups: CheckBox {
                        text: group.title;
                        checked: group.state;
                        toggled => {
                            root.group-edited(group.title, self.checked)
                        }
                    }
                }
            }
        }

        VerticalBox {
            text-edit := TextEdit {
                enabled: true;
                placeholder-text: "Текст повідомлення";
                wrap: word-wrap;
            }

            Button {
                text: "Відправити";
                clicked => {
                    send-message(text-edit.text)
                }
            }

            CheckBox {
                checked: root.autosend;
                text: "Відправляти автоматично";
                toggled => {
                    root.autosend-change(self.checked)
                }
            }
        }
    }
}