import { AboutSlint, VerticalBox, HorizontalBox, Button, CheckBox, TextEdit, LineEdit } from "std-widgets.slint";
import { MainScreen, LinkState, Group } from "main_screen.slint";
import { SettingsScreen, SendMode } from "settings_screen.slint";

enum Screen {
    main,
    settings,
}

export component App inherits Window {
    title: "Message Sender";
    preferred-height: 600px;
    preferred-width: 800px;

    in property <string> listener-ip;
    in-out property <[Group]> groups;
    in property <bool> autosend;
    property <Screen> screen: Screen.main;
    in property <SendMode> send-mode;
    in property <int> sync-interval;

    // To native code
    callback start-link <=> main-scr.start-link;
    callback sync();
    callback get-groups <=> main-scr.get-groups;
    callback group-edited <=> main-scr.group-edited;
    callback send-message <=> main-scr.send-message;
    callback autosend-change <=> main-scr.autosend-change;
    callback check-ip-correct <=> sett-scr.check-ip;
    callback send-mode-change <=> sett-scr.send-mode-change;
    callback sync-interval-changed <=> sett-scr.sync-interval-changed;

    // From native code
    callback set-qr <=> main-scr.set-qr;
    callback linked <=> main-scr.linked;
    callback synced <=> main-scr.synced;
    callback set-message-text <=> main-scr.set-message-text;

    // Actual UI
    main-scr := MainScreen {
        link-state: unlinked;
        groups: root.groups;
        autosend: root.autosend;
        width: 100%;
        height: 100%;
        settings => {
            root.screen = Screen.settings;
        }
        sync => {
            root.sync();
        }
        
        animate x {
             duration: 150ms;
             easing: ease-in-out;
        }
    }
    
    sett-scr := SettingsScreen {
        listener-ip: root.listener-ip;
        send-mode: root.send-mode;
        sync-interval: root.sync-interval;

        width: 100%;
        height: 100%;
        back => {
            root.screen = Screen.main;
        }
        sync => {
            root.sync();
        }

        animate x {
             duration: 150ms;
             easing: ease-in-out;
        }
    }

    states [
        main when screen == Screen.main: {
            main-scr.x: 0;
            sett-scr.x: -root.width;
        }
        settings when screen == Screen.settings: {
            main-scr.x: root.width;
            sett-scr.x: 0;
        }
    ]
}
