import { LineEdit, VerticalBox, HorizontalBox, Button, ComboBox, CheckBox } from "std-widgets.slint";

@rust-attr(derive(serde::Serialize, serde::Deserialize))
export enum SendMode {
    standard,
    frequency,
    debug,
}

component IpEdit inherits LineEdit {
    callback check-ip(text: string) -> bool;
    in-out property <bool> correct: true;

    edited(text) => {
        correct = check-ip(text)
    }
}

export component SettingsScreen {
    callback check-ip <=> listener-ip.check-ip;
    callback sync-interval-changed(int);
    callback back();
    callback send-mode-change(SendMode);
    callback sync <=> timer.triggered;
    callback send-timeout-changed(int);
    callback markdown-change(bool);
    callback parallel-send-changed(bool);

    in-out property <int> sync-interval;
    in-out property <int> send-timeout;
    in property <string> listener-ip;
    in property <SendMode> send-mode;
    in property <bool> markdown;
    in property <bool> parallel-send;

    function num-send-mode(mode: SendMode) -> int {
        if send-mode == SendMode.standard { return 0; }
        else if send-mode == SendMode.frequency { return 1; }
        else if send-mode == SendMode.debug { return 2; }
        return 0;
    }

    timer := Timer {
        interval: sync-interval * 1s;
        running: sync-interval == 0 ? false : true;
    }

    TouchArea {}

    VerticalBox {
        padding: 10px;

        VerticalLayout {
            spacing: 10px;
            alignment: start;

            HorizontalBox {
                Button {
                    icon: @image-url("icons/back.svg");
                    colorize-icon: true;
                    clicked => {
                        back()
                    }
                    width: self.preferred-width;
                }
                Text {
                    text: "Налаштування";
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    font-size: 18px;
                }
            }

            VerticalLayout {
                spacing: 2px;

                Text {
                    text: "IP-адреса прийому повідомлень";
                }
                listener-ip := IpEdit {
                    text: root.listener-ip;
                }
                Text {
                    text: "Щоб зміни цього параметру вступили у силу потрібно перезавантажити програму";
                    font-italic: true;
                }
            }

            VerticalLayout {
                spacing: 2px;

                Text {
                    text: "Інтервал автоматичного оновлення списку груп, с";
                }
                LineEdit {
                    text: sync-interval;
                    input-type: number;
                    edited(text) => {
                        root.sync-interval = text.to-float();
                        sync-interval-changed(root.sync-interval);
                    }
                }
            }

            VerticalLayout {
                spacing: 2px;

                Text {
                    text: "Таймаут для повторної відправки повідомлень, с";
                }
                LineEdit {
                    text: send-timeout;
                    input-type: number;
                    edited(text) => {
                        root.send-timeout = text.to-float();
                        send-timeout-changed(root.send-timeout);
                    }
                }
            }

            VerticalLayout {
                spacing: 2px;

                Text {
                    text: "Режим відправки повідомлень";
                }
                ComboBox {
                    current-index: num-send-mode(root.send-mode);
                    model: [
                        "Стандартний",
                        "З частотою",
                        "Як є",
                    ];
                    selected(current-value) => {
                        if self.current-index == 0 {
                            root.send-mode-change(SendMode.standard);
                        }
                        else if self.current-index == 1 {
                            root.send-mode-change(SendMode.frequency);
                        }
                        else if self.current-index == 2 {
                            root.send-mode-change(SendMode.debug);
                        }
                    }
                }
            }

            VerticalLayout {
                spacing: 2px;

                CheckBox {
                    checked: root.markdown;
                    toggled => {
                        root.markdown-change(self.checked);
                    }
                    text: "Відправляти повідомлення використовуючи форматування Markdown";
                }
            }

            VerticalLayout {
                spacing: 2px;

                CheckBox {
                    checked: root.parallel-send;
                    toggled => {
                        root.parallel-send-changed(self.checked);
                    }
                    text: "Відправляти повідомлення паралельно (НЕСТАБІЛЬНО!";
                }
            }
        }

        Text {
            text: "Version 0.1.0. Developed by ModernTy";
            horizontal-alignment: center;
            vertical-alignment: center;
            font-italic: true;
            height: self.preferred-height;
        }
    }
}